path: /kaggle/input/openlane-conv-to-yolov8n-seg/openlane-conv-to-yolov8n-seg
train: images/train
val: images/train


nc: 15
names: ['unkown', 'white-dash', 'white-solid', 'double-white-dash', 'double-white-solid', 'white-ldash-rsolid', 'white-lsolid-rdash', 'yellow-dash', 'yellow-solid', 'double-yellow-dash', 'double-yellow-solid', 'yellow-ldash-rsolid', 'yellow-lsolid-rdash', 'left-curbside', 'right-curbside']